version: $(VersionPrefix).{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
configuration:
  - Production
environment:
  VersionPrefix: 0.0.0
  VersionSuffix: dev
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(VersionPrefix)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(VersionPrefix)-$(VersionSuffix)

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 9)
  - node --version
  - npm --version

before_build:
  - nuget restore -Verbosity quiet
  - cd src\toofz.NecroDancer.WebClient
  - npm install
  - npm run build
  - cd ..\..
build:
  project: toofz.NecroDancer.WebClient.sln
  publish_wap: true
  verbosity: quiet

test_script:
  - cd src\toofz.NecroDancer.WebClient
  - node_modules\.bin\gulp build:js:test
  - node_modules\.bin\electron-mocha --opts .\tests\mocha-appveyor.opts
  - node_modules\.bin\remap-istanbul --input .\coverage\coverage-final.json --output .\coverage\coverage-final.json
  - node_modules\.bin\istanbul report --report lcovonly
  - node_modules\.bin\codecov --file=.\coverage\coverage\lcov.info --disable=gcov
  - cd ..\..

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
