version: $(VersionPrefix).{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
configuration:
  - Release
environment:
  VersionPrefix: 2.3.5
  VersionSuffix: alpha.3
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

install:
  - ps: Update-NodeJsInstallation 9.4.0
  - node --version
  - npm --version

before_build:
  - nuget restore -Verbosity quiet
  - cd src\toofz.NecroDancer.Web
  - npm install
  - npm run build
  - cd ..\..
build:
  project: toofz.NecroDancer.Web.sln
  verbosity: quiet
after_build:
  - dotnet publish src\toofz.NecroDancer.Web --output %APPVEYOR_BUILD_FOLDER%\dist

test_script:
  - cd src\toofz.NecroDancer.Web
  - node_modules\.bin\gulp build:js:test
  - node_modules\.bin\electron-mocha --opts .\tests\mocha-appveyor.opts
  - node_modules\.bin\remap-istanbul --input .\coverage\coverage-final.json --output .\coverage\coverage-final.json
  - node_modules\.bin\istanbul report --report lcovonly
  - node_modules\.bin\codecov --file=.\coverage\coverage\lcov.info --disable=gcov
  - cd ..\..

artifacts:
  - path: dist
    name: toofz.NecroDancer.Web
deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
