version: 2.0.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.WebClient
  COVERALLS_REPO_TOKEN:
    secure: RgfMtQ0AdNtC/Jr6cnC/8OZJBfj8VrRXa7yxcHdRrm0Gkch+6q2lUVXDUbz0BxTH
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: %APPVEYOR_JOB_ID%
build:
  project: $(PROJECT).sln
  publish_wap: true
  verbosity: minimal
cache:
  - packages -> **\packages.config
  - '%APPDATA%\npm-cache'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 8)
  - npm install --global npm
  - node --version
  - npm --version

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
  - cd %PROJECT%
  - npm install
  - npm run build
  - cd ..

test_script:
  - cd %PROJECT%
  - npm run test-appveyor
  - cd ..
