version: $(VersionPrefix).{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
    - '**\.idea\**\*'
configuration:
  - Release
environment:
  VersionPrefix: 2.3.14
  VersionSuffix: 
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

install:
  - ps: Install-Product node 9.4.0
  - node --version
  - npm --version

before_build:
  - nuget restore -Verbosity quiet
  - cd src\toofz.NecroDancer.Web
  - npm install
  - npm run build-prod
  - cd ..\..
build:
  project: toofz.NecroDancer.Web.sln
  verbosity: quiet
after_build:
  - dotnet publish src\toofz.NecroDancer.Web --output %APPVEYOR_BUILD_FOLDER%\dist

test_script:
  - cd src\toofz.NecroDancer.Web
  - npm run build-prod-test
  - node_modules\.bin\electron-mocha --opts test\mocha-appveyor.opts
  - node_modules\.bin\remap-istanbul --input coverage\coverage-final.json --output coverage\coverage-finaler.json
  - node_modules\.bin\istanbul report --include coverage\coverage-finaler.json --report lcovonly
  - node_modules\.bin\codecov --file=coverage\lcov.info --disable=gcov --root=..\..
  - cd ..\..

artifacts:
  - path: dist
    name: toofz.NecroDancer.Web
deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
