version: 2.3.4.{build}
image: Visual Studio 2017

branches:
  only:
    - master
configuration:
  - Production
environment:
  PROJECT: toofz.NecroDancer.WebClient
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)

install:
  - nuget update -Self
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 8)
  - npm install --global npm@5.3.0 codecov
  - node --version
  - npm --version

before_build:
  - appveyor-retry nuget restore -Verbosity quiet
  - cd %PROJECT%
  - npm install
  - npm run build
  - cd ..
build:
  project: $(PROJECT).sln
  publish_wap: true
  verbosity: minimal

test_script:
  - ps: .\Test-Project.ps1
after_test:
  - codecov --file="%PROJECT%\coverage\lcov.info" --disable=gcov

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true